services:
    app.admin.dblog:
        class: AdminBundle\Admin\DBLogAdmin
        #arguments: [~, AdminBundle\Entity\DBLog, AdminBundle\Controller\MigrationCRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Outil, label: DBLog }
        arguments:
            - null
            - AdminBundle\Entity\DBLog
            - AdminBundle:DBLogCRUD
        calls:
            - [ setTranslationDomain , [AdminStoreReceiptReceiptBundle]]
        public: true

    app.admin.dblogcorrespondence:
        class: AdminBundle\Admin\DBLogCorrespondenceAdmin
        arguments: [~, AdminBundle\Entity\DBLogCorrespondence, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Outil, label: MigrationID }
        public: true

    import.csvtoarray:
        class: AdminBundle\Services\ConvertCsvToArray