user_routing:
    resource: '@ApplicationSonataUserBundle/Resources/config/routing.yml'
    prefix:   /

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

builder_admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

site_routing:
    resource: "@SiteBundle/Resources/config/routing.yml"
    prefix:   /
    
builder_list:
    resource: "@BuilderListBundle/Resources/config/routing.yml"
    prefix:   /

builder_page:
    resource: "@BuilderPageBundle/Resources/config/routing.yml"
    prefix:   /

