# Site services for administration:

services:
  app.admin.actu:
    class: SiteBundle\Admin\ActuAdmin
    arguments: [~, SiteBundle\Entity\Actu, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Métier", label: "Actus" }
    public: true

  app.admin.comment:
    class: SiteBundle\Admin\CommentAdmin
    arguments: [~, SiteBundle\Entity\Comment, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Métier", label: "Commentaires" }
    public: true

  app.admin.lien:
    class: SiteBundle\Admin\LienAdmin
    arguments: [~, SiteBundle\Entity\Lien, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Métier", label: "Liens" }
    public: true

  app.admin.oeuvre:
    class: SiteBundle\Admin\OeuvreAdmin
    arguments: [~, SiteBundle\Entity\Oeuvre, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Métier", label: "Oeuvres" }
    public: true