#Routes pour l'espace d'administration (Sonata bundle)

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
  resource: .
  type: sonata_admin
  prefix: /admin

sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /admin/resetting

update_user_structure:
    path:  /profile
    defaults: { _controller: ApplicationSonataUserBundle:Profile:show }
    methods:  [POST]

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /
